// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq4yxgr7o0LAA0Xw0k4aiE_MRao11AvW4',
    appId: '1:650370662814:web:0157564a625cb44fc1d68f',
    messagingSenderId: '650370662814',
    projectId: 'wedding-halls-ddca2',
    authDomain: 'wedding-halls-ddca2.firebaseapp.com',
    storageBucket: 'wedding-halls-ddca2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1bfOQZZdFsDDieEcZf4JIyfp4wzTzwkk',
    appId: '1:650370662814:android:55e5d98058fa4ad2c1d68f',
    messagingSenderId: '650370662814',
    projectId: 'wedding-halls-ddca2',
    storageBucket: 'wedding-halls-ddca2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTRLAFwNPucef8iWFqtJQdQb-FpsGXD9o',
    appId: '1:650370662814:ios:2585be120a4d1f4fc1d68f',
    messagingSenderId: '650370662814',
    projectId: 'wedding-halls-ddca2',
    storageBucket: 'wedding-halls-ddca2.appspot.com',
    iosClientId: '650370662814-840k9lggjf961p7m535netdckhg9r3hd.apps.googleusercontent.com',
    iosBundleId: 'com.example.weddingHalls',
  );
}
